# KGEN Test Makefile
#
#

include ../Makefile.inc

CURR_DIR := $(shell pwd)
SRC_DIR := $(shell echo ${CURR_DIR} | sed s:tmp_:src/:)
TMP_DIR := ${CURR_DIR}/tmp_test
CALLSITE:=calling_module:calling_subroutine:add
ERR_FILE:=${CURR_DIR}/errors.log
FC_FLAGS:=$(shell cat ${SRC_DIR}/flags.txt &> /dev/null)

ifneq ("$(wildcard ${SRC_DIR}/kernel.f)", "")
	F77_TEST_UNPR := 1
	F77_TEST_PR := 0
	F90_TEST_UNPR := 0
	F90_TEST_PR := 0
endif

ifneq ("$(wildcard ${SRC_DIR}/kernel.f90)", "")
        F77_TEST_UNPR := 0
        F77_TEST_PR := 1
        F90_TEST_UNPR := 0
        F90_TEST_PR := 0
endif

ifneq ("$(wildcard ${SRC_DIR}/kernel.F)", "")
        F77_TEST_UNPR := 0
        F77_TEST_PR := 0
        F90_TEST_UNPR := 1
        F90_TEST_PR := 0
endif

ifneq ("$(wildcard ${SRC_DIR}/kernel.F90)", "")
        F77_TEST_UNPR := 0
        F77_TEST_PR := 0
        F90_TEST_UNPR := 0
        F90_TEST_PR := 1
endif

ifeq (${F77_TEST_UNPR}, 1)
	SRC := ${TMP_DIR}/calling_module.f
endif

ifeq (${F77_TEST_PR}, 1)
        SRC := ${TMP_DIR}/calling_module.f90
endif

ifeq (${F90_TEST_UNPR}, 1)
        SRC := ${TMP_DIR}/calling_module.F
endif

ifeq (${F90_TEST_PR}, 1)
        SRC := ${TMP_DIR}/calling_module.F90
endif



test: gendata
	@cd kernel; ${MAKE} -i >> ${ERR_FILE} 2>&1;
	@if grep -q "Verification PASSED" ${ERR_FILE} ; then \
		echo TEST ${TEST_DIR} passed >> ../Results.txt; \
		${MAKE} clean; \
	else \
		echo TEST ${TEST_DIR} FAILED. Check error log for more details >> ../Results.txt; \
	fi;

gendata: extract
	@if [ -d state ] ; then \
                cd state; make >> ${ERR_FILE} 2>&1; \
        else \
                echo extraction failed >> ${ERR_FILE} 2>&1; exit 1; \
        fi;

extract: copy
	@${KGEN_ROOT}/bin/kgen \
	    -D ROW=4,COLUMN=4 \
	    -I ${TMP_DIR} \
	    --state-build cmds="cd ${TMP_DIR}; make clean; make build" \
	    --state-run cmds="cd ${TMP_DIR}; make run" \
	    --kernel-compile FC='${FC}',FC_FLAGS='${FC_FLAGS}' \
	    ${SRC}:${CALLSITE} >>${ERR_FILE} 2>&1 ;


copy: mkdir
	@cp -rf ${SRC_DIR}/* ${TMP_DIR}

mkdir:
	@mkdir -p ${TMP_DIR} >${ERR_FILE} 2>&1

clean:
	@rm -rf ${TMP_DIR} kernel state kgen.log
